name: Build iOS IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Capacitor Sync
        run: |
          npx cap add ios
          npx cap sync
      - name: Build with Xcode
        run: |
          xcodebuild -workspace ios/App/App.xcworkspace -scheme App -sdk iphoneos -configuration Debug -archivePath $PWD/build/App.xcarchive CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" archive
          mkdir -p build/ipa
          cp -r build/App.xcarchive/Products/Applications/App.app build/ipa/
          cd build/ipa
          mkdir Payload
          mv App.app Payload/
          zip -r AniCLI.ipa Payload
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AniCLI-IPA
          path: build/ipa/AniCLI.ipa
